name: Python Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'  # Only trigger on Python file changes

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Required to post PR comments

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better context

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.py
          files_ignore: |
            **/test_*.py
            **/*_test.py
            **/tests/**
            **/__pycache__/**

      - name: Set up Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install --upgrade pip
          pip install google-adk requests

      - name: Run Python Codebase Reviewer
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Download review script
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/python_codebase_reviewer/github_actions/review_pr.py -o review_pr.py

          # Or if script is in the repo:
          # python python_codebase_reviewer/github_actions/review_pr.py

          python review_pr.py \
            --files "${{ steps.changed-files.outputs.all_changed_files }}" \
            --pr-number "$PR_NUMBER" \
            --repo "$REPO_NAME"

      - name: Post review results
        if: always() && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            // Check if review results file exists
            if (!fs.existsSync('review_results.md')) {
              console.log('No review results generated');
              return;
            }

            const reviewContent = fs.readFileSync('review_results.md', 'utf8');

            // Post comment on PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request?.number || context.payload.inputs?.pr_number,
              body: reviewContent
            });

      - name: Upload review results as artifact
        if: always() && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: code-review-results
          path: review_results.md
          retention-days: 30

      - name: Check for critical issues
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Fail the workflow if critical security issues found
          if [ -f review_results.md ]; then
            if grep -q "CRITICAL" review_results.md; then
              echo "::error::Critical security issues found in code review"
              exit 1
            fi
          fi
